### ISSUE TITLE
Regarding Connection String

### ISSUE THREAD

**Issue by tamilazhahanr** [JaCraig/SQLHelper#84]
**Describe the bug**
I have created the ASP.NET Core MVC application. And, created the separate class library for SQLHelperDB. I can't get the connection string from Appsetting.json file.

![image](https://github.com/JaCraig/SQLHelper/assets/79858560/fc7fd77c-d8d5-4bc1-8208-de5213dd6a79)

**Expected behavior**
I want to get the connection string from the Appsetting.json file instead of the hardcode

**Comment by JaCraig** [comment]
That's not really a bug. I'm assuming you're using the TestApp as an example based on the screenshot. That's more just a command line test app that I use sometimes. As far as IConfiguration and ASP.Net, depending on the version, the WebApplication.CreateBuilder already creates an IConfiguration object and adds it to the services: 

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0

Basically, you don't have to do anything for it to read the connection string other than put it into the file and supply the IConfiguration object from services. Either that or just call for one from the IoC container built into ASP.Net and it'll fill that in automatically. Also, you can remove that module. The AddCanisterModules() bit on the service collection is just so the system can wire itself correctly. You don't need to create any yourself unless you want to use them to break up your services.
